name: Erlang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:25.0.2

    steps:
    - uses: actions/checkout@v3
    - name: Run validation checks
      working-directory: erlang
      run: rebar3 check
    - name: Release can be built
      working-directory: erlang
      run: rebar3 as prod release

